### ISSUE TITLE
Release of profile requested but WebEnginePage still not deleted. Expect troubles !

### ISSUE THREAD

**Issue by munzirtaha** [xiaoyifang/goldendict-ng#955]
When I close goldendict-ng, I always get this warning:
Release of profile requested but WebEnginePage still not deleted. Expect troubles !

**OS and software versions:**

Operating System: Arch Linux 
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Qt Version: 6.5.1
Kernel Version: 6.4.2-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 9 6900HX with Radeon Graphics
Memory: 30.5 GiB of RAM

**Comment by xiaoyifang** [comment]
can you try this branch fix/profile-release

**Comment by munzirtaha** [comment]
The warning indeed disappeared but I got

====reading  0 of (10799) bytes . Finished: 1
QResource '/bullet.gif' not found or is empty
js: jQuery.Deferred exception: qt is not defined ReferenceError: qt is not defined
    at HTMLDocument.<anonymous> (gdlookup://localhost?word=hello&group=4294967294:8:26)
    at e (qrc:///scripts/jquery-3.6.0.slim.min.js:2:30244)
    at t (qrc:///scripts/jquery-3.6.0.slim.min.js:2:30546) undefined
article view loaded url: "gdlookup://localhost?word=hello&group=4294967294" true
js: Uncaught ReferenceError: qt is not defined

**Comment by xiaoyifang** [comment]
seems like a js console warning.

**Comment by munzirtaha** [comment]
It's fixed now, thanks for your great support.
